# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 2, 22, 19, 25, 842769, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packs',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 2, 22, 19, 37, 444693, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
