# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20160903_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CommaSeparatedIntegerField(choices=[('1', '\u041f\u0435\u0440\u0432\u044b\u0439'), ('2', '\u0412\u0442\u043e\u0440\u043e\u0439'), ('3', '\u0422\u0440\u0435\u0442\u0438\u0439'), ('4', '\u0427\u0435\u0442\u0432\u0435\u0440\u0442\u044b\u0439'), ('5', '\u041f\u044f\u0442\u044b\u0439')], default='1', max_length=10),
        ),
    ]
