# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_question_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a1',
            field=models.CharField(max_length=50, verbose_name='\u041f\u0435\u0440\u0432\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='question',
            name='a2',
            field=models.CharField(max_length=50, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='question',
            name='a3',
            field=models.CharField(max_length=50, verbose_name='\u0422\u0440\u0435\u0442\u0438\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='question',
            name='a4',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0427\u0435\u0442\u0432\u0435\u0440\u0442\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='question',
            name='a5',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u041f\u044f\u0442\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
    ]
